### ISSUE TITLE
Nodes not showing on .66.1

### ISSUE THREAD

**Issue by frogbite** [jkeljo/hassio-addons#1]
I just installed this addon in hass.io .66.1 and in the webui, no nodes show.   I tried both selecting the "usb" option and filling in the device name.  This is running on a pi3.

**Comment by frogbite** [comment]
I got the device name from the configuration.yaml

zwave:                                                                    
    usb_path: /dev/ttyACM0

**Comment by jkeljo** [comment]
The add-on makes no changes to OZW or OZWCP, so chances are if there’s a
bug, it would also repro on a standalone installation of OZWCP on a Pi3.
That said, post up some logs and I’ll see if anything jumps out at me.

**Comment by frogbite** [comment]
Finally got it working.  It is fussy and not because of your addon, it is just fussy.  I had initially selection the USB option and it gave an error when pressing initialize that it could not find the serial port.  When first starting if you put in the /dev device first it does work as expected.  

So the issue is that if you put in the wrong device or select USB, it must crash ozwcp.  Hard to see this in the hass.io docker though other than seeing the error message in the OZW_log.

Thanks
