### ISSUE TITLE
Reloading ozwcp in browser crashes it

### ISSUE THREAD

**Issue by frogbite** [jkeljo/hassio-addons#2]
If I do a reload in the browser where it is running it appears to crash.  I then need to restart homeassistant with the hassio command to go back in and restart ozwcp.

**Comment by jkeljo** [comment]
The add-on makes no changes to OZW or OZWCP, so chances are if there’s a
bug, it would also repro on a standalone installation of OZWCP on a Pi3.
That said, post up some logs and I’ll see if anything jumps out at me.

**Comment by frogbite** [comment]
The issue is that ozwcp had already crashed, this is why the reload was failing.
