### ISSUE TITLE
Add-on crashes, brings instability to entire system

### ISSUE THREAD

**Issue by magnusoverli** [jkeljo/hassio-addons#3]
Hi!

I was very glad to find this add-on. I have been missing the ability to run OZWCP.
I installed the add-on without issues. Started the add-on and got the interface up in my browser. Then the add-on seemingly went down. The browser could no longer connect to the interface. I was already logged in over ssh, so I tried to start home assistant again. Nothing happened, could not connect to the HA interface. I initiated a host reboot from the ssh console, and now nothing starts. I can ping the network interface, but that is about it. I cannot log in over ssh anymore and neither the HA or OZWCP interfaces come up.

I guess I will come back with more info when I have something useful to bring to the table.

Running hassio 0.69.0.b3 on Raspberry Pi 3, using the Aeotec Z-stick gen 5.

**Comment by jkeljo** [comment]
Oof, I’m very sorry to hear about that; it sounds incredibly frustrating.

Hass.io add-ons are Docker containers kept largely isolated from one
another. The only state this add-on and OZWCP share with Hass.io itself is
ZWave related, which shouldn’t be able to prevent booting HA altogether. :(

One thing that does come to mind is that because this is a locally built
add-on, installing it pulls and builds OZW and OZWCP. That’s a lot of I/O
on an SD card, which is why installing it takes so long. Could be the SD
card is now full, or, if you’ve been using it for a while, all that I/O
pushed it over its maximum lifetime writes. (I wouldn’t expect the latter
with a newish card; I run on a Pi too and I installed the add-on dozens of
times during testing.)

Either way, I’d suggest pulling the SD card, putting it in another computer
(flip the lock switch first so that the other computer can’t mess with the
card), and see what you can see. Ideally you’d either be able to find HA
boot logs that tell why it’s not starting, or run some diagnostics on the
card itself.

**Comment by magnusoverli** [comment]
Hi again!

I understand that, add-ons being docker containers, they should not interfere with each other. 
I just got home, pulled the power and tried starting my Pi from scratch. It worked! That's the good news.

The bad news is that the exact same thing happened now when I tried to use OZWCP. Clicked the "Open WebUI"-button, chose "USB" interface, clicked initialize, and the whole system went down. I am still able to interact with the ssh console, so I will hold off rebooting it for some time if you think I can pull some info from the system to get a better understanding of why this happens...
The SD-card apparently have plenty of space left and, while it isn't new anymore, the fact that I can pull the power and get it back online indicates to me that it is OK.

```
core-ssh:~# df -h
Filesystem                Size      Used Available Use% Mounted on
none                     13.7G      4.1G      8.8G  32% /
tmpfs                   486.1M         0    486.1M   0% /dev
tmpfs                   486.1M         0    486.1M   0% /sys/fs/cgroup
/dev/mmcblk0p2          294.1M    216.8M     61.8M  78% /dev/init
/dev/mmcblk0p6           13.7G      4.1G      8.8G  32% /data
/dev/mmcblk0p6           13.7G      4.1G      8.8G  32% /config
/dev/mmcblk0p6           13.7G      4.1G      8.8G  32% /ssl
/dev/mmcblk0p6           13.7G      4.1G      8.8G  32% /addons
/dev/mmcblk0p6           13.7G      4.1G      8.8G  32% /backup
/dev/mmcblk0p6           13.7G      4.1G      8.8G  32% /share
/dev/mmcblk0p6           13.7G      4.1G      8.8G  32% /etc/resolv.conf
/dev/mmcblk0p6           13.7G      4.1G      8.8G  32% /etc/hostname
/dev/mmcblk0p6           13.7G      4.1G      8.8G  32% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                   486.1M         0    486.1M   0% /proc/timer_list
tmpfs                   486.1M         0    486.1M   0% /proc/timer_stats
tmpfs                   486.1M         0    486.1M   0% /proc/sched_debug
tmpfs                   486.1M         0    486.1M   0% /sys/firmware
```

**Comment by jkeljo** [comment]
Glad to hear things weren’t permanently broken!  

That sounds like OZWCP going into a tight loop and eating up all the CPU or something.  

I don’t think there’s anything you’ll be able to see over ssh now that won’t also be there after you get it working again. Once you get back into HA, go to the ozwcp add-on page and you should see logs from OZWCP itself at the bottom. Those might give a clue as to what’s going on.

**Comment by magnusoverli** [comment]
The log is not showing up in the HA interface... Can I access them from the console or in any other way?

**Comment by magnusoverli** [comment]
Managed to pull the log:
```
[19:57:43+0200] INFO ----> Stopping hass.io to avoid network, config, and log conflicts...
[19:57:52+0200] INFO ----> Starting ozwcp...
2018-05-08 19:57:52.390 Always, OpenZwave Version 1.4.2992 Starting Up
webserver starting port 8090
Warning: MHD_USE_THREAD_PER_CONNECTION must be used only with MHD_USE_INTERNAL_POLLING_THREAD. Flag MHD_USE_INTERNAL_POLLING_THREAD was added. Consider setting MHD_USE_INTERNAL_POLLING_THREAD explicitly.
post: key=dev data=Z-stick size=7
post: key=fn data=open size=4
2018-05-08 19:58:37.292 Warning, Failed - Network Key Not Set
post: key=usb data=true size=4
post: key=usb data= size=0
2018-05-08 19:58:37.298 Error, Cannot find specified HID port with VID:1b5f and PID:0x0001.
2018-05-08 19:58:37.298 Error, Enumerating connected HIDs:
2018-05-08 19:58:37.299 Error, Failed to open HID port HID Controller
/root/ozwcp.sh: line 29:    24 Segmentation fault      (core dumped) /root/open-zwave-control-panel/ozwcp
```

**Comment by magnusoverli** [comment]
Do you see anything that seems close to explaining what is happening?

**Comment by jkeljo** [comment]
Did setting the network key help?

Could be something to do with selecting the USB interface. The way I work with OZWCP is to enter the device name (`usb_path` from your `zwave` section in `configuration.yaml`) and click Initialize.

**Comment by jkeljo** [comment]
I'm going to close this now, but feel free to reopen if there's anything further I can do to help.

**Comment by Swiftnesses** [comment]
Same issue here, totally crashes my system when initialising USB...
