### ISSUE TITLE
v1.0.2 Installation issue

### ISSUE THREAD

**Issue by aniceberg** [jkeljo/hassio-addons#4]
I'm trying to install this on a Raspberry Pi 3 B running HassOS 1.9 with Home Assistant 0.75.2 but the install button just spins for a second and then turns red and stops.

**Comment by jkeljo** [comment]
Can you include the logs? Install logs are visible on the system tab.

**Comment by aniceberg** [comment]
Sorry about that-

> 18-08-09 15:57:34 INFO (SyncWorker_4) [hassio.docker.addon] Start build 13861ffc/aarch64-addon-ozwcp:1.0.2
> 18-08-09 15:57:36 ERROR (SyncWorker_4) [hassio.docker.addon] Can't build 13861ffc/aarch64-addon-ozwcp:1.0.2: pull access denied for hassioaddons/base-arch64, repository does not exist or may require 'docker login'

**Comment by jkeljo** [comment]
Well, that was dumb on my part. Looks like I had a typo in the build file. Just bumped to 1.0.3 with the fix.
