### ISSUE TITLE
 Fails to start on hassio 0.79.3

### ISSUE THREAD

**Issue by ymoona** [jkeljo/hassio-addons#5]
Log reports:
INFO ----> Stopping hass.io to avoid network, config, and log conflicts...
parse error: Expected string key before ':' at line 1, column 4
[16:11:46+0200] ERROR ----> Unknown HTTP error occured

It used to work with older versions. Any I do test/debug work around?

**Comment by Paul-dH** [comment]
I have the exact same issue on 79.1

**Comment by danlinn** [comment]
Same

**Comment by olbj** [comment]
I have the same issue on hassio 0.79.2

**Comment by AlphaSupreme** [comment]
Same issue here.

**Comment by jondye** [comment]
I've got the same. Is this something to do with the new auth system that was made live in 0.77 and updated in 0.78 and 0.79?

**Comment by ArnoutVerbeken** [comment]
See https://github.com/home-assistant/hassio/issues/692.
Another addon I use had the same problem (looks like the same at least) but was not able to solve it yet.
See https://github.com/mr-bjerre/hassio-remote-backup/issues/9

**Comment by jkeljo** [comment]
Thanks for the reports, all! I’ve been on vacation, but I’m back now and will have a look later today.

**Comment by ymoona** [comment]
Not sure, bit this may help https://github.com/mr-bjerre/hassio-addons/commit/4a817c93b335e99001de59f33ab599f43e040553
