### ISSUE TITLE
Error Installing Add-on

### ISSUE THREAD

**Issue by iAutom8** [jkeljo/hassio-addons#6]
Getting the following error when installing.  I have tried several times with no luck.  Running Home Assistant 0.89.1 on HassOS 2.10 on a RPi 3B.

```
19-03-13 16:57:02 INFO (SyncWorker_16) [hassio.docker.addon] Start build 13861ffc/armv7-addon-ozwcp:1.0.4
19-03-13 17:00:01 ERROR (SyncWorker_16) [hassio.docker.addon] Can't build 13861ffc/armv7-addon-ozwcp:1.0.4: The command '/bin/sh -c make' returned a non-zero code: 2
```

**Comment by Kriegdich** [comment]
Same problem here on HassIO 0.89.2

**Comment by jkeljo** [comment]
Well, crap... I've stopped using a Pi for my local system, and it's building fine on my NUC with HassOS 2.10 & 0.89.2. :( I'll need to dig out the Pi and see about a repro.

**Comment by Papsnoek** [comment]
I have the Same issue. Im using an Odroid XU4
